# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "DZRRRRRR"
repo_name: "my_arxiv_daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Diffusion":
        filters: ["diffusion models", "SDE", "ODE"]
    "Implicit": 
        filters: ["Implicit Neural"]
    "UnderWater":
        filters: ["underwater enhancement"]
    "image_dehaze":
        filters: ["image dehaze"]
    "Restoration":
        filters: ["image restoration"]
    "Image_Translation":
        filters: ["Image Translation", "unpair"]

