title: CV Arxiv Daily
description: Automatically Update CV Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/DZRRRRRR/my_arxiv_daily
  another_url: https://github.com/DZRRRRRR/my_arxiv_daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter: AlphaRealcat
  github: vincentqyw

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-seo-tag
